apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v7m84mdtt-python 
  janus-idp.io/tekton: v7m84mdtt-python
  backstage.io/kubernetes-id: v7m84mdtt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v7m84mdtt-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml