apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v7m84mdtt-python
  janus-idp.io/tekton: v7m84mdtt-python
  backstage.io/kubernetes-id: v7m84mdtt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v7m84mdtt-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
